language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

script:
  - composer install
  - vendor/bin/phpunit
