language: php

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE forge;

script: composer install
script: vendor/bin/phpunit
